build:
	g++ walsh.cpp -o walsh
	g++ statistics.cpp -o statistics
	g++ prinel.cpp -o prinel
	g++ crypto.cpp -o crypto
	g++ regele.cpp -o regele

run-p1: walsh
	./walsh

run-p2: statistics
	./statistics

run-p3: prinel
	./prinel

run-p4: crypto
	./crypto

run-p5: regele
	./regele

walsh:
	g++ walsh.cpp -o walsh

statistics:
	g++ statistics.cpp -o statistics

prinel:
	g++ prinel.cpp -o prinel

crypto:
	g++ crypto.cpp -o crypto

regele:
	g++ regele.cpp -o regele

clean:
	rm -r walsh
	rm -r statistics
	rm -r regele
	rm -r crypto
	rm -r prinel

.PHONY: pack clean

