# Copyright 2021 - 2022 - 321CA - Mihai Daniel Soare
build:
	g++ curatare.cpp -o curatare
	g++ fortificatii.cpp -o fortificatii
	g++ beamdrone.cpp -o beamdrone
	g++ curse.cpp -o curse

run-p1: curatare
	./curatare

run-p2: fortificatii
	./fortificatii

run-p3: beamdrone
	./beamdrone

run-p4: curse
	./curse

curatare:
	g++ curatare.cpp -o curatare

fortificatii:
	g++ fortificatii.cpp -o fortificatii

beamdrone:
	g++ beamdrone.cpp -o beamdrone

curse:
	g++ curse.cpp -o curse

clean:
	rm -r curatare
	rm -r fortificatii
	rm -r curse
	rm -r beamdrone

.PHONY: clean

